# Generated by Django 5.0.1 on 2024-01-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
