# Generated by Django 5.0.1 on 2024-02-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_user_managers_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
